services:
  - type: web
    name: ai-content-creation-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn run:app
    envVars:
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false 